### PR TITLE
Make default gateway IP '.1' instead of '.254'

### PR DESCRIPTION
**Pull request by emtuls**
Having the default gateway be set to the common default IP address of the Virtual Adapter (`.1`) fixes an issue where FakeNet expects to be able to reach out of the guest via the DHCP server which it assumes is at `.254`.

The DHCP server is only at `.254` if using VMware and the last address in the IP pool for DHCP is `.254`, which is fairly common, but this is not the case on VirtualBox. VirtualBox uses 1 IP address less than the lowest address in the IP pool for DHCP and thus, FakeNet does not work out of the box for VirtualBox.

If we instead use the IP Address of the Virtual Adapter created by VMware and VirtualBox, which is typically the `.1` address, we can make FakeNet work out of the box for both of these platforms.

Context wise, this is for a Host-Only network for a guest VM where DHCP is enabled.

### CODE REVIEW

**Comment by thejoelpatrol** [comment]
It has been a while since I have tried it, but last time I used VirtualBox, .1 did not work for the gateway with the current version of FakeNet at that time

https://github.com/mandiant/flare-fakenet-ng/issues/168

**Comment by emtuls** [comment]
@thejoelpatrol That is interesting...
I have never hit the issue of FakeNet not being able to set the Gateway like that. 

In all of my testing, it always sets it to `.254` which it shows here: https://github.com/mandiant/flare-fakenet-ng/blob/ac33a706274d3e567080d261f7886fd472378ffa/fakenet/diverters/winutil.py#L366

And that of course fails in VirtualBox due to it not being the DHCP server (at least not by default) or the Virtual Adapter address.
Here is that default on version `1.4.11` (most of my testing was on version `3.0-alpha`)
image


And here is the change to `.1` with the pings working:
image

**Comment by thejoelpatrol** [comment]
@emtuls thanks for all that testing. I can't explain why it didn't work for me at that time, I didn't dig into the FakeNet code to try to understand it fully beyond just figuring out how to reproduce it locally. I hope it was something specific to my setup that was uncommon. But just something to be aware of, in case it's one of those bugs that goes away by itself and then comes back by itself.

**Comment by tinajohnson** [comment]
Thanks for the PR, @emtuls! Tested from my end as well and the fix works smoothly.

**Review by strictlymike — APPROVED** [review]
Approved for pre-release

**Pull request merged**
